# This is a basic workflow to help you get started with Actions

name: Deploy to server

# Controls when the action will run.
on:
  # Triggers the workflow on a push to the main branch
  push:
    branches: [main]
  # Allow manual trigger
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # https://stackoverflow.com/a/61236896
      - name: Tar repository
        run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf deploy.tar ../build/

      - name: Cleaning up existing setup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          # take down docker compose
          script: |
            cd ~
            docker-compose -p lthc-app down
            rm -rf ~/LTHC && mkdir ~/LTHC

      - name: Adding environment variables
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          # create .env file with env keys
          script: |
            cd ~/LTHC
            touch .env && rm .env
            echo REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }} >> .env
            echo REACT_APP_APP_ID=${{ secrets.REACT_APP_APP_ID }} >> .env
            echo REACT_APP_AUTH_DOMAIN=${{ secrets.REACT_APP_AUTH_DOMAIN }} >> .env
            echo REACT_APP_PROJECT_ID=${{ secrets.REACT_APP_PROJECT_ID }} >> .env
            echo REACT_APP_STORAGE_BUCKET=${{ secrets.REACT_APP_STORAGE_BUCKET }} >> .env
            echo REACT_APP_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_MESSAGING_SENDER_ID }} >> .env
            echo REACT_APP_MEASUREMENT_ID=${{ secrets.REACT_APP_MEASUREMENT_ID }} >> .env
            echo REACT_APP_LTHC_PASS=${{ secrets.REACT_APP_LTHC_PASS }} >> .env
          # TODO get LTHC_FRONTEND_PORT env

      - name: Copy repository to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: 'deploy.tar'
          target: '~/LTHC/'

      - name: Setup app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/LTHC
            tar xf deploy.tar && rm deploy.tar && mv build/* . && rm -rf build/

      - name: Start docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          command_timeout: 200m
          # cd into respective directory and start docker
          script: |
            cd ~/LTHC
            docker-compose -p lthc-app up -d
